# this service provisions a mongo database container for local development and testing,
# using environment variables defined in .env to set up authentication.

services:
  vinder.identity.provider.infrastructure.mongo.database:
    container_name: "vinder.identity.provider.database"
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - vinder.identity.provider.infrastructure.mongo.database:/data/db

volumes:
  vinder.identity.provider.infrastructure.mongo.database: