# this service provisions a MongoDB container for local development and testing,
# using environment variables defined in .env to set up authentication.

services:
  vinder.identity.provider.infrastructure.mongo.database:
    container_name: "vinder.identity.provider.database"
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - vinder.identity.provider.infrastructure.mongo.database:/data/db

  vinder.identity.provider:
    container_name: "vinder.identity.provider"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      Settings__Database__ConnectionString: ${MONGO_CONNECTIONSTRING}
      Settings__Database__DatabaseName: ${MONGO_DATABASENAME}
      Settings__Security__SecretKey: ${VINDER_IDENTITY_PROVIDER_SECRETKEY}
      Settings__Administration__Username: ${VINDER_IDENTITY_PROVIDER_ADMIN_USERNAME}
      Settings__Administration__Password: ${VINDER_IDENTITY_PROVIDER_ADMIN_PASSWORD}
      Settings__Administration__Tenant: ${VINDER_IDENTITY_PROVIDER_ADMIN_TENANT}
    depends_on:
      - vinder.identity.provider.infrastructure.mongo.database

volumes:
  vinder.identity.provider.infrastructure.mongo.database: